test: Add missing unit tests URLEndpointListener
couchbase/couchbase-lite-ios pull request #2780
Opened 2020-11-25 04:45 UTC by jayahariv

* add missing unit tests for URLEndpointListener - ObjC

2020-11-26 05:09 UTC, jayahariv commented on Objective-C/Tests/URLEndpointListenerTest.m
> +
```suggestion
```

2020-11-30 19:32 UTC, pasin requested changes

2020-11-30 19:32 UTC, pasin commented on Objective-C/Internal/Replicator/CBLTrustCheck.mm
> +        CBLLogVerbose(WebSocket, @"Server SSL certificate is not self-signed, force trusting...");
I think there is a bug here that it should return nil instead of doing force trust.

2020-12-10 06:01 UTC, pasin requested changes

2020-12-10 06:17 UTC, jayahariv commented
I was using the same name which Android unit test uses(only for those missing tests).

2020-12-10 06:26 UTC, jayahariv commented on Swift/Tests/URLEndpointListenerTest.swift
> +    func testTLSSelfSignedClientAuthenticatorWithChainedCredentials() throws {
this test is chained certs server & accept self signed client, which should reject non-self-signed server.  

`testAcceptSelfSignedWithNonSelfSignedChainedCerts`?

2020-12-11 09:17 UTC, jayahariv commented on Objective-C/Tests/URLEndpointListenerTest.m
> +
```suggestion
```

2020-12-11 09:42 UTC, jayahariv commented
Renamed all tests

2020-12-11 23:53 UTC, pasin approved these changes

2020-12-12 00:04 UTC, merged