CBL-1910: update to maxAttempts
couchbase/couchbase-lite-ios pull request #2840
Opened 2021-05-20 09:23 UTC by jayahariv

2021-05-21 04:02 UTC, pasin requested changes

2021-05-21 04:02 UTC, pasin commented on Swift/ReplicatorConfiguration.swift
> +    public var heartbeat: TimeInterval {
I feel like this should be an optional type (for any optional configs). But this can be explored and done as a separate ticket.

2021-05-21 04:02 UTC, pasin commented on Swift/ReplicatorConfiguration.swift
> +    public var maxAttempts: Int {
I feel like this should be an optional type (for any optional configs). But this can be explored and done as a separate ticket.

2021-05-21 04:02 UTC, pasin commented on Swift/ReplicatorConfiguration.swift
> +    public var maxAttemptWaitTime: TimeInterval {
I feel like this should be an optional type (for any optional configs). But this can be explored and done as a separate ticket.

2021-05-21 04:02 UTC, pasin commented on Swift/Tests/ReplicatorTest.swift
> +        XCTAssertEqual(config.maxAttemptWaitTime, 300)
The expected value is 0.

2021-05-21 04:02 UTC, pasin commented on Swift/Tests/ReplicatorTest.swift
> +        XCTAssertEqual(config.maxAttemptWaitTime, 300)
The expected value is 0.

2021-05-21 04:02 UTC, pasin commented on Swift/Tests/ReplicatorTest.swift
> +        XCTAssertEqual(repl.config.maxAttemptWaitTime, 300)
The expected value is 0.

2021-05-21 04:02 UTC, pasin commented on Swift/Tests/ReplicatorTest.swift
> +        XCTAssertEqual(config.maxAttempts, 10)
The expected value is 0.

2021-05-21 04:02 UTC, pasin commented on Swift/Tests/ReplicatorTest.swift
> +        XCTAssertEqual(config.maxAttemptWaitTime, 300)
The expected value is 0.

2021-05-21 04:02 UTC, pasin commented on Swift/ReplicatorConfiguration.swift
> +    private static let defaultHeartbeat: TimeInterval = 300
We don't maintain these values in CBL.

2021-05-21 12:16 UTC, jayahariv commented on Objective-C/Tests/ReplicatorTest+Main.m
> +    config.maxAttempts = 3; // (initial) + 2 + 2
initial request time + 2 seconds + 2 seconds

2021-05-24 22:29 UTC, pasin requested changes
I have one comment left. Apart fro

2021-05-24 22:29 UTC, pasin commented on Swift/ReplicatorConfiguration.swift
> +    private static let defaultHeartbeat: TimeInterval = 300
I don't think we need these anymore.

2021-05-24 23:10 UTC, jayahariv commented on Swift/ReplicatorConfiguration.swift
> +    private static let defaultHeartbeat: TimeInterval = 300
wait, did I not remove this!! :-|

2021-05-25 07:53 UTC, jayahariv commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +        [_logic addValue: cookie forHTTPHeaderField: @"Cookie"];
```suggestion
        [_logic addValue: cookie  forHTTPHeaderField: @"Cookie"];
```

2021-05-25 21:34 UTC, pasin approved these changes

2021-05-25 21:34 UTC, pasin commented on Objective-C/Tests/ReplicatorTest+Main.m
> +    [self testMaxAttempt: -1 count: 9 continuous: NO];
Use 0 instead of -1.

2021-05-25 21:34 UTC, pasin commented on Objective-C/Tests/ReplicatorTest+Main.m
> +    [self testMaxAttempt: -1 count: 9 continuous: NO];
typos: ~13mints

2021-05-26 00:28 UTC, merged