CBL-2363: No overfil assertion when replicator waiting for idle
couchbase/couchbase-lite-ios pull request #2886
Opened 2021-09-28 13:32 UTC by jayahariv

* No overfil assertion when replicator waiting for idle. (Only enabled them for replicator with idle status expectations)
* disabled the logging with unit test, this will only start showing up any race condition for us(even un-reproducible ones)

2021-09-28 13:53 UTC, jayahariv commented
CI failures are disabled here: #2887

2021-09-29 02:44 UTC, jayahariv commented
@pasin Do you think we should only make this noAssertExpectation to only the flaky unit tests. Since that's more accurate.

2021-09-29 06:10 UTC, pasin requested changes

2021-09-29 06:10 UTC, pasin commented on Objective-C/Tests/CBLTestCase.h
> +- (XCTestExpectation*) noAssertExpectationWithDescription:(NSString *)description;
I think noAssert could be misleading. Maybe 'allowOverfillExpectation...?

2021-09-29 06:10 UTC, pasin commented on Objective-C/Tests/ReplicatorTest.m
> +    XCTestExpectation* x = [self noAssertExpectationWithDescription:@"Replicator idle"];
We don't need to do it here as the listener will be removed when it's idle.

2021-09-29 06:10 UTC, pasin commented on Swift/Tests/MessageEndpointTest.swift
> +        let x3 = self.noAssertExpectation(description: "Replicator Stopped")
There shouldn't be multiple stopped.

2021-09-29 06:10 UTC, pasin commented on Swift/Tests/ReplicatorTest.swift
> +        let x1 = self.noAssertExpectation(description: "#1 repl finish")
Multiple stopped is unexpected.

2021-09-29 06:10 UTC, pasin commented on Swift/Tests/ReplicatorTest.swift
> +        let x2 = self.noAssertExpectation(description: "#2 repl finish")
Multiple stopped is unexpected.

2021-09-29 19:32 UTC, pasin approved these changes

2021-09-30 01:01 UTC, merged