CBL-1410: LiveQuery to use C4QueryObserver
couchbase/couchbase-lite-ios pull request #2900
Opened 2021-10-09 07:52 UTC by jayahariv

* remove CBL handling
* use LC API directly
* disable the expiry doc unit test

2021-11-19 03:38 UTC, pasin requested changes
Please make sure the following cases are covered:

1. When adding a second listener after the first listener is notified, the second listener should get the change (current result).

2. When having more than one listeners, each listener should have independent result set. This means that both listeners should be able to iterate through the result correct when getting the same change notified.

3. Change the parameters should result to a new query and a new change notified.

4. Test that the changes are coalescing. This test could be that after the first notification, create 2 docs. The change could be notified only once, not two.

2021-11-19 03:38 UTC, pasin commented on Objective-C/Internal/CBLQueryChangeNotifier.h
> +- (NSUInteger) removeChangeListenerWithToken: (id<CBLListenerToken>)token;
It doesn't seem to get used so I think it is better to just do void.

2021-11-19 08:16 UTC, jayahariv commented
Regarding the tests, will keep them in a separate PR CBL-2582

2021-11-19 18:06 UTC, pasin requested changes

2021-11-19 18:06 UTC, pasin commented on Objective-C/CBLListenerToken.h
> +@protocol CBLListenerToken <NSObject, NSCopying>
Ugh, I don't think we should NSCopying as this means that our API allows the token to be copied :(. So reverting back to use UUID  as a key is better. Sorry for this.

2021-11-19 18:06 UTC, pasin commented on Objective-C/CBLQuery.mm
> +            [NSException raise: NSInvalidArgumentException
Can you also log the error for the case that somebody experiences a crash due to this so they have some info in the log?

2021-11-19 18:06 UTC, pasin commented on Objective-C/CBLQuery.mm
> +                [NSException raise: NSInvalidArgumentException
Can you also log the error for the case that somebody experiences a crash due to this so they have some info in the log?

2021-11-20 03:19 UTC, jayahariv commented on Objective-C/Internal/CBLChangeListenerToken.m
> +
```suggestion
```

2021-11-20 03:58 UTC, pasin approved these changes

2021-11-20 04:24 UTC, merged