Enable TLSDomain for Log
couchbase/couchbase-lite-ios pull request #2937
Opened 2022-02-10 07:12 UTC by jayahariv

2022-02-15 09:55 UTC, jayahariv commented on Objective-C/CBLLog.mm
> +        setNamedLogDomainLevel("Zip", kC4LogDebug);
Zip and TLS > enabled for default Database domains?

2022-02-17 18:04 UTC, pasin commented
TLS is NETWORK.

2022-02-18 01:26 UTC, jayahariv commented on Objective-C/CBLLog.mm
> +                              @"Zip": @(kCBLLogDomainNetwork),
```suggestion
                              @"Zip": @(kCBLLogDomainNetwork),
                              @"TLS": @(kCBLLogDomainNetwork),
```

2022-02-18 01:46 UTC, pasin requested changes

2022-02-18 01:46 UTC, pasin commented on Objective-C/CBLLog.mm
> +                              @"Zip": @(kCBLLogDomainNetwork),
MISSING TLS which should be in Network domain.

2022-02-18 01:46 UTC, pasin commented
Once this is merged, please share the change to the other platform.

2022-02-18 01:53 UTC, jayahariv commented on Objective-C/CBLLog.mm
> +                              @"TLS": @(kCBLLogDomainNetwork),
^^^

2022-02-18 01:58 UTC, pasin approved these changes

2022-02-18 02:00 UTC, merged