Add network interface option in the replicator config
couchbase/couchbase-lite-ios pull request #2944
Opened 2022-02-23 10:00 UTC by jayahariv

* Add network interface option in the replicator config
* cherry-pick - d71b4428d73756ef4f0d7e5ee4640aa09d8b71ae

* We should have a functional test for this feature.

2022-02-24 12:51 UTC, jayahariv commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +
```suggestion
```

2022-02-24 16:56 UTC, pasin requested changes

2022-02-24 16:56 UTC, pasin commented on Objective-C/CBLReplicatorConfiguration.h
> +@property (nonatomic, nullable) NSString* networkInterface;
We could also enhance this to support both Interface Name and IP Address in the future.

2022-02-24 16:56 UTC, pasin commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +            NSString* m = [NSString stringWithFormat: @"failed to set network interface %@ %s",
I think we should include the info about addr->ai_family, addr->ai_socktype, addr->ai_protocol here too.

2022-02-24 16:56 UTC, pasin commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +        NSString* m = [NSString stringWithFormat: @"failed to create socket, %s", strerror(errno)];
I think we should include addr->ai_family, addr->ai_socktype, addr->ai_protocol in the log as well.

2022-02-24 16:56 UTC, pasin commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +
I think we should do a verbose log about the info getting from getaddrinfo (addr->ai_family, addr->ai_socktype, addr->ai_protocol).

2022-02-25 04:59 UTC, pasin requested changes

2022-02-25 04:59 UTC, pasin commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +            [self populateError: error errNo: res msg: msg];
No need to check `if (res == EAI_NONAME)`. Just convert all EAI Error. CBLStatus will taken care of the error mapping from getaddrinfo().

```
    if (res) {
        NSString* msg = [NSString stringWithFormat: @"failed(%d) to get address info: %s", res, gai_strerror(res)];
        CBLWarnError(WebSocket, @"%@: %@", self, msg);
        if (error) {
                *error = [NSError errorWithDomain: (id)kCFErrorDomainCFNetwork
                                                                  code: kCFHostErrorUnknown
                                                             userInfo: @{NSLocalizedDescriptionKey : msg, (id)kCFGetAddrInfoFailureKey: @(res}];
         }
         return false;
    }
```

2022-02-25 05:01 UTC, pasin commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +- (bool) populateError: (NSError**)error errNo: (int)errNo msg: (NSString*)msg {
Maybe populatePOSIXError?

2022-02-25 05:57 UTC, pasin commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +- (bool) populateError: (NSError**)error errNo: (int)errNo msg: (NSString*)msg {
populateError is fine.

2022-02-28 05:30 UTC, jayahariv commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +static inline NSError* posixError(int errNo, NSString* msg) {
👍🏻

2022-02-28 05:30 UTC, jayahariv commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +static inline NSString* addrInfo(const struct addrinfo* addr) {
👍🏻

2022-02-28 05:39 UTC, jayahariv commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +                result = setsockopt(_sockfd, IPPROTO_IPV6, IPV6_V6ONLY, &index, sizeof(index));
My search was inadequate, I couldn't find the `IPV6_BOUND_IF` flag in the documentation. I looked only at `IPV6_MULTICAST_IF`(which was not working), `IPV6_V6ONLY`. 

Now I can see, it's correct to set `IPV6_BOUND_IF` with interface index.

2022-02-28 05:59 UTC, jayahariv commented
[tests.txt](https://github.com/couchbase/couchbase-lite-ios/files/8150919/tests.txt)

For reference, attaching the tests we used.

2022-02-28 06:21 UTC, jayahariv commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +            queueName = [NSString stringWithFormat: @"%@-Connecting", queueName];
```suggestion
            queueName = [NSString stringWithFormat: @"%@-SocketConnect", queueName];
```

2022-03-01 02:08 UTC, pasin approved these changes

2022-03-01 02:20 UTC, merged