CBL-2973:  Check for the pin-cert with all certs in the chain
couchbase/couchbase-lite-ios pull request #2958
Opened 2022-04-07 07:24 UTC by jayahariv

* Check for the pin-cert with all certs in the chain

2022-04-13 13:07 UTC, jayahariv commented
Jenkins CI Failure is not related
Jira ticket - https://issues.couchbase.com/browse/CBL-3011

2022-04-13 18:28 UTC, pasin requested changes
I think we should always have PR validation green unless it's really not possible. I recommended to fix PR validation first otherwise we won't be able to use the benefit of the PR validation.

2022-04-13 18:28 UTC, pasin commented on Objective-C/Tests/ReplicatorTest+Main.m
> +    NSURL* url = [NSURL URLWithString: @"wss://localhost:4986/itunes"];
I think there is no need to test with itunes which is big. Testing with scratch (empty) is fine.

2022-04-13 18:28 UTC, pasin commented on Objective-C/Tests/ReplicatorTest+Main.m
> +    self.disableDefaultServerCertPinning = YES;    // without this, SSL handshake will fail
I understand that this doesn't pin a non-matched as stated in the test name `testMultipleCertSGWithNonMatchingCert_SG`. Can you pin a non matched or make it into a separate this b/w testing non-match and testing no-pin-cert.

2022-04-13 18:28 UTC, pasin commented on Objective-C/Tests/ReplicatorTest+Main.m
> + */
I have updated LiteCore's test to use the cert chain. The new files with be `sg_cert.pem`, `sg_key.pem`, and `cert.pem` (only leaf).

2022-04-13 18:28 UTC, pasin commented on Objective-C/Tests/ReplicatorTest+Main.m
> + */
https://github.com/couchbase/couchbase-lite-core/commit/a6401bdcf3580fd71699e4e71b0c8b5abc309942

2022-04-13 18:28 UTC, pasin commented on Objective-C/Tests/ReplicatorTest+Main.m
> +    id target = [self remoteEndpointWithName: @"itunes" secure: YES];
Same as above. Just test with scratch.

2022-04-13 18:28 UTC, pasin commented on Objective-C/Tests/ReplicatorTest+Main.m
> +- (SecCertificateRef) certChains: (NSString*)name {
This method is getting only one cert and cert chain. Probably change to `getCert:`?

2022-04-13 18:28 UTC, pasin commented on Objective-C/Tests/ReplicatorTest+Main.m
> +- (SecCertificateRef) certChains: (NSString*)name {
Alternatively, you can try something like this. If it works, you just use the PEM string in the test without creating the DER file. I did this in LiteCore test.

```
NSString* pem = "<CERT IN PEM format>"
NSData *certData = [[NSData alloc] initWithBase64Encoding: pem];
SecCertificateRef parsedCertificate = SecCertificateRef cert = SecCertificateCreateWithData(NULL, (__bridge CFDataRef)certData);
```

2022-04-22 16:57 UTC, pasin approved these changes
Two comments, the rest looks good to me.

2022-04-22 16:57 UTC, pasin commented on Objective-C/Tests/ReplicatorTest+Main.m
> +    target = [[CBLURLEndpoint alloc] initWithURL: url];
Seem like this is not needed as it has been done here:
```
id target = [self remoteEndpointWithName: @"scratch" secure: YES];
```

2022-04-22 16:57 UTC, pasin commented on Objective-C/Tests/ReplicatorTest+Main.m
> +    target = [[CBLURLEndpoint alloc] initWithURL: url];
Same as above comment.

2022-04-25 13:58 UTC, merged