Scope initial
couchbase/couchbase-lite-ios pull request #2964
Opened 2022-05-25 07:34 UTC by jayahariv

2022-05-26 07:09 UTC, jayahariv commented on Objective-C/CBLQuery.mm
> +
```suggestion
```

2022-05-27 00:13 UTC, pasin requested changes

2022-05-27 00:13 UTC, pasin commented on Objective-C/CBLReplicatorConfiguration.h
> + @param config Respective configuration for the collection, if nil, default config */
Maybe just Configuration for the collection?

2022-05-27 00:13 UTC, pasin commented on Objective-C/CBLScope.h
> +@protocol CBLScope <NSObject>
Missing API doc.

2022-05-27 00:13 UTC, pasin commented on Objective-C/CBLScope.h
> +- (CBLCollection*) getCollectionWithName: (NSString*)name;
collectionWithName:

2022-05-27 00:13 UTC, pasin commented on Objective-C/CBLScope.h
> +- (NSArray<CBLCollection*>*) getCollections;
collections

2022-05-27 00:13 UTC, pasin commented on Objective-C/CBLScope.h
> +@protocol CBLScope <NSObject>
I think it's unnecessary for iOS to have protocol for CBLScope and Could be CBLCollection as well. 

Even though the spec said "Protocol", it's up to the platform to decide whether to have it or not. I believe Java will not have it as protocol. Let evaluate this when you implement it.

2022-05-27 03:03 UTC, jayahariv commented on Objective-C/CBLQuery.mm
> +        return [self initWithCollection: (CBLCollection*)from.source JSONRepresentation: json];
I will add a TODO, if we use the defaultCollection now, it will start failing all the QueryTests.

2022-05-27 03:25 UTC, jayahariv commented
Failure is not due to this PR, new commits on the lite-core-EE `master` branch causing failure with the current lite-core `staged` commit.

2022-05-27 03:29 UTC, pasin commented
Isn't Lite-Core EE from iOS-EE's submodule?

2022-05-27 03:30 UTC, jayahariv commented
No, its checking for branch-name(PR-##), or current target('master', release/XXX) 
https://github.com/couchbase/couchbase-lite-ios/blob/master/Jenkinsfile#L41

2022-05-27 03:33 UTC, pasin commented
I don't remember why it clones LiteCore-EE directly instead of getting it from iOS-EE. It seems like it's better to get it from iOS-EE.

2022-05-27 03:33 UTC, pasin approved these changes

2022-05-27 03:40 UTC, jayahariv commented
Since script was copied from LiteCore, which was using it to make sure, related `lite-core-EE` PR also taken into account. Which never failed till now, now realized that is not necessary, instead take it from `lite-ios-EE` submodule. 

Will make the change CBL-3208

2022-05-27 03:47 UTC, merged