Scope initial swift
couchbase/couchbase-lite-ios pull request #2965
Opened 2022-06-03 09:47 UTC by jayahariv

2022-06-03 20:45 UTC, pasin requested changes
The PR is big so I might not catch everything.

2022-06-03 20:45 UTC, pasin commented on Objective-C/CBLCollection.h
> + `CBLCollection` is ref-counted and is owned by the database object that creates it. Hence,
This is not related to Objective-C as user will not do call retain() or release(). Can you revise this?

2022-06-03 20:45 UTC, pasin commented on Objective-C/CBLDatabase.h
> +- (NSArray<CBLScope*>*) scopes;
nullable and could return error now.

2022-06-03 20:45 UTC, pasin commented on Objective-C/CBLDatabase.h
> +- (NSArray<CBLCollection*>*) collections: (nullable NSString*)scope;
nullable and could return error now.

2022-06-03 20:45 UTC, pasin commented on Objective-C/CBLDatabase.h
> +- (NSArray<CBLScope*>*) scopes;
Please check the latest email about API change.

Here at the list of API that could return an error.
```
**Collection (Section 5.2, 5.5)**
Indexes() -> [String]
getDocument(id: String) -> Document?

**Scope (Section 5.4)**
getCollections() -> [Collection]
getCollection(name: String) -> Collection?
 
**Database (Section 5.6.2 , 5.6.3)**
getDefaultCollection() -> Collection?
getDefaultScope() -> Scope
getScopes() -> [Scope]
getScope(name: String) -> Scope?
getCollections(scope: String? = kDefaultScopeName) -> [Collection]
getCollection(name: String, scope: String? = kDefaultScopeName) -> Collection?
```

2022-06-03 20:45 UTC, pasin commented on Objective-C/CBLDatabase.mm
> +- (nullable CBLScope*) scopeWithName: (NSString*)name {
Could return an error now.

2022-06-03 20:45 UTC, pasin commented on Objective-C/CBLIndexable.h
> +- (NSArray<NSString*>*) indexes;
Could return an error.

2022-06-03 20:45 UTC, pasin commented on Objective-C/CBLReplicatorConfiguration.h
> +/**
There is also a `collections` property.

2022-06-03 20:45 UTC, pasin commented on Objective-C/CBLScope.h
> +@interface CBLScope : NSObject <CBLQueryFactory>
Scope doesn't implement CBLQueryFactory now. We discard this feature in helium.

2022-06-03 20:45 UTC, pasin commented on Objective-C/CBLScope.h
> +- (nullable CBLCollection*) collectionWithName: (NSString*)name;
Could return an error.

2022-06-03 20:45 UTC, pasin commented on Objective-C/CBLScope.m
> +- (CBLQuery*) createQuery: (NSString*)query error: (NSError**)error {
Remove

2022-06-03 20:45 UTC, pasin commented on Swift/Collection.swift
> +/// A `CBLCollection` represent a collection which is a container for documents.
No CBL

2022-06-03 20:45 UTC, pasin commented on Swift/Collection.swift
> +/// ## CBLCollection Lifespan
This section is not valid for Swift. Please review this section.

2022-06-03 20:45 UTC, pasin commented on Swift/Collection.swift
> +    func document(id: String) -> Document? {
Could throw

2022-06-03 20:45 UTC, pasin commented on Swift/Collection.swift
> +    public func indexes() -> [String] {
Could throw

2022-06-03 20:45 UTC, pasin commented on Swift/Indexable.swift
> +    func indexes() -> [String]
Could throws

2022-06-03 20:45 UTC, pasin commented on Swift/Indexable.swift
> +    // Database class will not implementthis protocol
Agree

2022-06-03 20:45 UTC, pasin commented on Swift/ReplicatorConfiguration.swift
> +    public func getCollectionConfig(_ collection: Collection) -> CollectionConfiguration {
CollectionConfiguration is nullable.

2022-06-03 20:45 UTC, pasin commented on Swift/Scope.swift
> +    public func collections() -> [Collection] {
Could throws

2022-06-03 20:45 UTC, pasin commented on Swift/Scope.swift
> +    public func collection(name: String) -> Collection? {
Could throws

2022-06-03 20:45 UTC, pasin commented on Swift/Database.swift
> +    public func collections(scope: String? = defaultScopeName) -> [Collection] {
Could throws

2022-06-03 20:45 UTC, pasin commented on Swift/Database.swift
> +    public func defaultCollection() -> Collection? {
Could throws

2022-06-03 20:45 UTC, pasin commented on Swift/Database.swift
> +    public func scope(name: String) -> Scope? {
Could throws

2022-06-03 20:45 UTC, pasin commented on Swift/Database.swift
> +    public func scopes() -> [Scope] {
Could throws

2022-06-03 20:45 UTC, pasin commented on Swift/Database.swift
> +    public func defaultScope() -> Scope {
Could throws

2022-06-03 20:45 UTC, pasin commented on Swift/Database.swift
> +    public func collection(name: String, scope: String? = defaultScopeName) -> Collection? {
Could throws

2022-06-03 20:46 UTC, pasin commented
I just noticed that the PR was marked as draft, but please look at my review comment.

2022-06-06 06:54 UTC, jayahariv commented
I waited for the checks to pass to make it ready, but forgot. Sure, it was ready, when I assigned.

2022-06-07 02:17 UTC, pasin requested changes

2022-06-07 02:17 UTC, pasin commented on Swift/Collection.swift
> +/// return CBLErrorNotOpen while accessing the collection APIs.
`throw an NSError with the CBLError.notOpen code while ...`

2022-06-07 02:17 UTC, pasin commented on Swift/Collection.swift
> +    /// CBLErrorNotOpen code will be thrown if the collection is deleted
CBLErrorNotOpen > An error with CBLError.notOpen code or `CBLError.notOpen code`.

Similarly for the other methods as well.

2022-06-07 02:17 UTC, pasin commented on Swift/Collection.swift
> +    func getDocumentExpiration(id: String) -> Date? {
throws

2022-06-07 02:17 UTC, pasin commented on Swift/DataSource.swift
> +    @available(*, deprecated, message: "Use database.defaultCollection().saveDocument(:) instead.")
Wrong message.

2022-06-07 02:17 UTC, pasin commented on Swift/Database+Query.swift
> +    @available(*, deprecated, message: "Use database.defaultCollection().indexes instead.")
indexes()

2022-06-07 02:17 UTC, pasin commented on Swift/Scope.swift
> +public final class Scope {
Add a description.

2022-06-07 02:17 UTC, pasin commented on Objective-C/CBLScope.h
> +#import "CBLQueryFactory.h"
Remove

2022-06-07 02:17 UTC, pasin commented on Objective-C/CBLScope.h
> +/**
Please revise CBLScope Lifespan as it's not valid.

2022-06-07 02:17 UTC, pasin commented on Swift/CollectionConfiguration.swift
> +public struct CollectionConfiguration {
Add a short description.

2022-06-07 02:17 UTC, pasin commented on Swift/CollectionChangeObservable.swift
> +public protocol CollectionChangeObservable {
Add a short description.

2022-06-07 02:17 UTC, pasin commented on Swift/Indexable.swift
> +public protocol Indexable {
Add a short description.

2022-06-07 02:17 UTC, pasin commented on Swift/QueryFactory.swift
> +public protocol QueryFactory {
Add a short description.

2022-06-07 02:17 UTC, pasin commented on Objective-C/CBLCollectionChangeObservable.h
> +@protocol CBLCollectionChangeObservable <NSObject>
Add a short description.

2022-06-07 02:17 UTC, pasin commented on Objective-C/CBLQueryFactory.h
> +@protocol CBLQueryFactory <NSObject>
Add a short description.

2022-06-07 18:03 UTC, pasin approved these changes

2022-06-08 03:54 UTC, merged