test: 8.14 replicator
couchbase/couchbase-lite-ios pull request #2990
Opened 2022-07-28 11:32 UTC by jayahariv

* Add unit tests for replicator+collection support
* Not tested now, will be tested and updated once the LC API update PR is merged

2022-08-11 17:07 UTC, pasin requested changes

2022-08-11 17:07 UTC, pasin commented on Objective-C/Tests/ReplicatorTest+Collection.m
> +- (void) _testMismatchedCollectionReplication {
Is there an issue created?

2022-08-11 17:07 UTC, pasin commented on Objective-C/Tests/ReplicatorTest+Collection.m
> +- (void) _testCollectionGetPendingDocumentIDs {
This issue was fixed.

2022-08-11 17:07 UTC, pasin commented on Objective-C/Tests/ReplicatorTest+Collection.m
> +- (void) _testCollectionIsDocumentPending {
This issue was fixed.

2022-08-12 00:14 UTC, jayahariv commented on Objective-C/CBLLog.mm
> -                              @"SQL": @(kCBLLogDomainDatabase),
there was a slack conversation about removing or making it to debug log level. Since the information is not that useful,  I chose to remove it.

2022-08-12 00:29 UTC, pasin approved these changes

2022-08-12 00:43 UTC, merged