[debug] add log to show the IP Address when connecting the socket
couchbase/couchbase-lite-ios pull request #3037
Opened 2022-11-03 15:39 UTC by jayahariv

2022-11-04 15:52 UTC, pasin requested changes

2022-11-04 15:52 UTC, pasin commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +        char *ip = inet_ntoa((struct in_addr)addr->sin_addr);
I think this function is only for IPV4.

2022-11-04 15:52 UTC, pasin commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +        char *ip = inet_ntoa((struct in_addr)addr->sin_addr);
inet_ntop supports both.

2022-11-05 17:51 UTC, jayahariv commented
Not tested ipv6 address, but ipv4 works fine. will do test today

2022-11-06 16:53 UTC, pasin requested changes

2022-11-06 16:53 UTC, pasin commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +            if (inet_ntop(AF_INET, &addr->sin_addr, addrBuf, INET_ADDRSTRLEN) != NULL) {
These two line doesn't match :
char addrBuf[MAX(**INET_ADDRSTRLEN, INET6_ADDRSTRLEN**)];
if (inet_ntop(AF_INET, &addr->sin_addr, addrBuf, **INET_ADDRSTRLEN**)

2022-11-06 16:53 UTC, pasin commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +    CBLLogVerbose(WebSocket, @"event code: %lx - stream: %@", (unsigned long)eventCode, stream);
We have logged on every single event. This is not necessary.

2022-11-07 05:19 UTC, pasin approved these changes

2022-11-07 05:21 UTC, merged