Update iOS Deployment Target to 11.0
couchbase/couchbase-lite-ios pull request #3162
Opened 2023-06-20 19:20 UTC by velicuvlad

Besides the relevant project config change, the rest of updates are within tests or utility functions - so no affect on the product itself

2023-06-20 19:44 UTC, pasin requested changes
For minimum change in release branch, please only change the version in xcconfig file.

2023-06-20 19:44 UTC, pasin commented on CouchbaseLite.xcodeproj/project.pbxproj
> +				MACOSX_DEPLOYMENT_TARGET = 10.14;
Don't do it here in project.pbxproj.

2023-06-20 19:44 UTC, pasin commented on Objective-C/Internal/Replicator/CBLTrustCheck.mm
> +    if (@available(iOS 12.0, *)) {
For minimum change in release branch, let do not change this.

2023-06-20 19:44 UTC, pasin commented on Objective-C/Internal/Replicator/CBLTrustCheck.mm
> +    if (@available(iOS 12.0, *)) {
For minimum change in release branch, let do not change this.

2023-06-20 19:44 UTC, pasin commented on Objective-C/Internal/Replicator/CBLWebSocket.mm
> +                _clientIdentity = toSecIdentityWithCertChain(c4cert, &error);
For minimum change in release branch, let do not change this.

2023-06-20 19:44 UTC, pasin commented on Objective-C/Tests/PredictiveQueryTest+CoreML.m
>  @interface PredictiveQueryWithCoreMLTest : CBLTestCase
For minimum change in release branch, let do not change this.

2023-06-20 19:44 UTC, pasin commented on Objective-C/Tests/PredictiveQueryTest+CoreML.m
> +    if (@available(iOS 12.0, *)) {
For minimum change in release branch, let do not change this.

2023-06-20 20:03 UTC, pasin requested changes

2023-06-20 20:03 UTC, pasin commented on Package.swift
> +        .iOS(.v11), .macOS(.v10_14)
We will do this change when releasing 3.1.1.

2023-06-21 00:42 UTC, jianminzhao commented
Looks good to me, but @pasin is the expert.

2023-06-21 00:43 UTC, jianminzhao approved these changes

2023-06-21 01:28 UTC, pasin approved these changes

2023-06-21 13:20 UTC, merged