CBL-5324: Vector Index Tests 1-5
couchbase/couchbase-lite-ios pull request #3230
Opened 2024-02-15 19:19 UTC by velicuvlad

- First 5 vector search tests passing on local
- Update LiteCore to 3.2.0-137

Disabled tests so that they dont run in Jenkins as the library doesn't exist.

2024-02-15 20:35 UTC, velicuvlad commented
Once you open the project with XCode, add the vector search extension under `Frameworks` in root directory and set as follows: 
![image](https://github.com/couchbase/couchbase-lite-ios/assets/23612597/83e16eda-a5df-4ac7-87ee-1199b5b02922).

2024-02-15 21:12 UTC, pasin requested changes

2024-02-15 21:12 UTC, pasin commented on Objective-C/Tests/CBLTestCase.m
> +    [self initDB];
Should call [self openDB] otherwise if calling this in the VectorSearchTest, it will do the copy again.

2024-02-15 21:12 UTC, pasin commented on Objective-C/Tests/VectorSearchTest.m
> +- (NSString*) databasePath: (NSString*)fileName inDirectory: (NSString*)dir {
Better to move this method to CBLTestCase so it can be shared with MigrationTest.

2024-02-15 21:12 UTC, pasin commented on Objective-C/Tests/VectorSearchTest.m
> +    [collection createIndexWithName: @"words_index" config: config error: &error];
Assert the boolean result to check that the create index was successful.

```
Assert([collection createIndexWithName: @"words_index" config: config error: &error]);
```

2024-02-15 21:12 UTC, pasin commented on Objective-C/Tests/VectorSearchTest.m
> +    CBLMutableArray* dinnerArray = [[CBLMutableArray alloc] initWithData: kDinnerVector];
You can just do [parameters setValue: kDinnerVector forName: @"vector"].

2024-02-15 21:12 UTC, pasin commented on Objective-C/Tests/VectorSearchTest.m
> +    NSString* explain = [q explain: &error];
More readable when having an empty line before this line as explain is not related to set parameter at all.

2024-02-16 18:05 UTC, pasin commented
The testCollectionConflictResolver failure is not related to this PR. I have fixed the bug in the test in 3.1 branch and that needs to be ported here.

2024-02-16 18:06 UTC, pasin approved these changes

2024-02-16 18:20 UTC, merged