CBL-5514: Swift MutableDocument's collection is not set when a new document is saved
couchbase/couchbase-lite-ios pull request #3287
Opened 2024-05-14 17:09 UTC by velicuvlad

- change Document.collection API to have a private setter
- set collection on save
- add 1 tests for each side (Obj-C and Swift)

2024-05-15 14:52 UTC, velicuvlad commented
Tests failing is unrelated to this PR. Somewhat flaky as it seems the timeout period is not big enough... all of them pass on local. Will investigate as part of the code coverage ticket.

2024-05-15 15:02 UTC, bmeike approved these changes
Be sure you get confirmation from someone who actually knows what they are doing, for this.  There was *lots* of discussion during the original implementation of Collections, about whether the platform code was allowed to hold the reference to one, or not.  I believe the issue is that the thing to which you hold a reference might become invalid, behind your back.    Worth checking.

2024-05-15 15:38 UTC, velicuvlad commented
I can confirm that this is behaviour is already there for Obj-C. The Obj-C tests are just to confirm the behaviour.

A new MutableDoc is getting created without any collection ref, meanwhile it gets one when it is saved (as part of the process). I initially thought the change would be bigger as I didn't know that Swift has private setters (Pasin made me aware - kudos). For Swift the collection attribute was non-modifiable as it was a `let`.

What exactly do you refer as getting invalid? The C4Collection object? We do not allow the change of `doc.collection` so in the case you want to move a document, a brand new copy must be made anyway... I would expect that if the collection is invalid by magic, as it cannot be changed, that document is pretty much orphan and the solution becomes the same -> make a brand new copy of it

When we pull a doc out of the db, it does come attached with a collection so we already hold ref to it. I can't think of a case for which that collection would be invalided at the exact time of the save, when save is a collection operation - so if doesn't exist it will fail on save in the first place

2024-05-15 15:45 UTC, pasin requested changes

2024-05-15 15:45 UTC, pasin commented on Swift/Collection.swift
> +        }
This should be done after saving is successful.

2024-05-15 15:45 UTC, pasin commented on Swift/Collection.swift
> +        if (document.collection == nil){
Format: A space after ).

2024-05-15 15:45 UTC, pasin commented on Swift/Collection.swift
> +        }
There are another two save functions that need set the collection to the saved doc as well.

2024-05-20 03:08 UTC, pasin approved these changes

2024-05-20 13:11 UTC, merged