CBL-3385: Allow null expression parameter for Function.count(expression)
couchbase/couchbase-lite-ios pull request #3290
Opened 2024-06-03 13:42 UTC by velicuvlad

2024-06-03 14:16 UTC, velicuvlad commented
failing tests unrelated, there's a hope to address these in a another, already existing, PR.

2024-06-03 17:04 UTC, bmeike approved these changes
LGTM

2024-06-03 17:04 UTC, bmeike commented on Swift/Function.swift
> +        if let expression = expression {
I'm not sure what idiomatic Obj-C looks like so ignore this if it is irrelevant.
I would be inclined to have the value of the `let` be either expression.toImpl() or expression.property('*) and to have a single return statement.

2024-06-03 17:49 UTC, pasin requested changes

2024-06-03 17:49 UTC, pasin commented on Swift/Function.swift
> +            return QueryExpression(CBLQueryFunction.count(Expression.property("*").toImpl()))
If expression is nil, nil can be passed to Objective-C count directory.

```
return QueryExpression(CBLQueryFunction.count(expression != nil ? expression.toImpl() : nil))
```

2024-06-03 17:49 UTC, pasin commented on Swift/Function.swift
> +            return QueryExpression(CBLQueryFunction.count(Expression.property("*").toImpl()))
Need to update the `+ (CBLQueryExpression*) count: (CBLQueryExpression*)expression;` signature to allow null as well.

2024-06-06 04:02 UTC, pasin approved these changes

2024-06-06 13:32 UTC, merged