CBL-6070: Implement Database Full-Sync Option
couchbase/couchbase-lite-ios pull request #3318
Opened 2024-08-01 17:38 UTC by velicuvlad

- cherry picked 5c10248b9ecaf27c08b8f43d7f7f5996d9d54eb7 from `release/3.1` branch. A couple of small, easy-to-resolve conflicts - nothing important
- Implemented FullSync DatabaseConfiguration property.
- Only Obj-C tests do check for c4db_config2 kC4DB_DiskSyncFull flag
- Update to LiteCore 3.2.0-223

2024-08-02 22:57 UTC, velicuvlad commented
the build failure is due to one of the tests... still investigating if is just the test or not. The PR has nothing to do with the failure itself, I dont know why it hasn't failed at the time the test was introduced and also why it just doesn't like it for macos - everything is fine on local.

2024-08-03 00:34 UTC, pasin commented
It's build issue in test. Not sure why it's happening now. It can be fixed by this:

```
[self expectError: CBLErrorDomain code: CBLErrorNotOpen in: ^BOOL(NSError** err) {
        return [col indexWithName: @"index1" error: err] != nil;
}];
```

2024-08-03 00:36 UTC, pasin requested changes

2024-08-03 00:36 UTC, pasin commented on Swift/DatabaseConfiguration.swift
> +    /// As Couchbase Lite normally configures its databases, There is a very
Same with the previous PR. Small T?.

2024-08-03 00:36 UTC, pasin commented on Swift/DatabaseConfiguration.swift
> +    /// power failure will not cause the loss of any data.  FULL synchronous
Extra space.

2024-08-05 14:44 UTC, pasin approved these changes

2024-08-05 14:46 UTC, merged