CBL-6191 : Fix null URL for proxy CONNECT request (#3324)
couchbase/couchbase-lite-ios pull request #3331
Opened 2024-10-07 14:25 UTC by velicuvlad

NSURL cannot be created with only host and port anymore starting from iOS 17. Changed to use CFURLCreateWithString directly.

2024-10-08 18:35 UTC, pasin requested changes

2024-10-08 18:35 UTC, pasin commented on Objective-C/Internal/Replicator/CBLHTTPLogic.m
> +        CFURLRef requestURL = CFURLCreateWithString(kCFAllocatorDefault, (__bridge CFStringRef)destination, false);
I just noticed that the last parameter is false. It should be NULL. I guess objective is kind of converting false to NULL but it should be fixed here and in 3.2 branch as well.

2024-10-10 18:09 UTC, bmeike approved these changes
I have no idea what is going on here. :-)
 I'm going to assume that it is necessary and correct.

2024-10-11 19:07 UTC, pasin approved these changes

2024-10-11 19:09 UTC, pasin commented
@bmeike 

From iOS 17, `NSURL's URLWithString:` function doesn't allow to create an URL without scheme anymore but we do need this for requesting a proxy's CONNECT request. So we are using a low level CFURLCreateWithString to create CFRULRef directly instead.

2024-10-11 20:08 UTC, bmeike commented
Wow.  Now I get it!

2024-10-14 14:17 UTC, merged