CBL-6307: Databaes MMap Configuration API and tests
couchbase/couchbase-lite-ios pull request #3333
Opened 2024-10-15 19:18 UTC by velicuvlad

Includes:
- LiteCore 3.2.1-9.
- both Obj-C and Swift impl and tests.
- Defaults re-generated to include both fullSync and mmap.
- sign test targets and iOS test app under Couchbase team to land on real device.

2024-10-16 22:49 UTC, pasin requested changes

2024-10-16 22:49 UTC, pasin commented on Objective-C/CBLDatabase.mm
> +#if !TARGET_OS_OSX
We don't need this guard as LiteCore will decide what to do.

2024-10-16 22:49 UTC, pasin commented on Objective-C/Tests/DatabaseTest.m
> +#endif
No guardrails anymore for macOS.

2024-10-16 22:52 UTC, bmeike approved these changes
Looks good to me

2024-10-17 17:21 UTC, pasin approved these changes

2024-10-18 11:14 UTC, merged